"""Shared shopping intent taxonomy."""

from app.utils.taxonomy import (
    BROWSE_KEYWORDS,
    BUY_READY_KEYWORDS,
    CATEGORY_ALIASES,
    CATEGORY_KEYWORDS,
    CORE_MISSING_FIELDS,
    INTENT_ALIASES,
    OUT_OF_SCOPE_INTENT,
    OUT_OF_SCOPE_KEYWORDS,
    PREFERENCE_ALIASES,
    PREFERENCE_KEYWORDS,
    RULE_PREFERENCE_ALIASES,
    SCENARIO_ALIASES,
    SCENARIO_KEYWORDS,
    SHOPPING_TARGET_KEYWORDS,
    UNSUPPORTED_PLATFORM_CLAIMS,
)

__all__ = [
    "BROWSE_KEYWORDS",
    "BUY_READY_KEYWORDS",
    "CATEGORY_ALIASES",
    "CATEGORY_KEYWORDS",
    "CORE_MISSING_FIELDS",
    "INTENT_ALIASES",
    "OUT_OF_SCOPE_INTENT",
    "OUT_OF_SCOPE_KEYWORDS",
    "PREFERENCE_ALIASES",
    "PREFERENCE_KEYWORDS",
    "RULE_PREFERENCE_ALIASES",
    "SCENARIO_ALIASES",
    "SCENARIO_KEYWORDS",
    "SHOPPING_TARGET_KEYWORDS",
    "UNSUPPORTED_PLATFORM_CLAIMS",
]
