services:
  backend:
    build:
      context: .
    container_name: buywise-backend
    env_file:
      - path: .env
        required: false
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - ./data:/app/data
      - ./vector_store:/app/vector_store
      - ./uploads:/app/uploads

  mysql:
    image: mysql:8.0
    container_name: buywise-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: oxygen
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
