"""Broad deterministic products for guide fallback demo flows."""

from __future__ import annotations

from decimal import Decimal
from typing import Any


DEMO_BROAD_PRODUCTS: list[dict[str, Any]] = [
    {
        "id": 1301,
        "name": "CrispAir 4L 易洗空气炸锅",
        "category": "空气炸锅",
        "brand": "HomeChef",
        "sku": "demo-broad-air-fryer-crispair-4l",
        "price": Decimal("329.00"),
        "original_price": Decimal("429.00"),
        "platform": "京东",
        "product_url": "https://www.mi.com/global/product/xiaomi-smart-air-fryer-pro-4l/",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/beta-lamp-benq-genie/silver-4-61e4114f52932eb8.jpg",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/beta-lamp-benq-genie/silver-4-61e4114f52932eb8.jpg"],
        "rating": Decimal("4.70"),
        "sales": 2100,
        "description": "4L 容量空气炸锅，适合租房做饭，内胆易清洗，占地不大。",
        "specs": {"capacity": "4L", "cleaning": "可拆洗炸篮", "power": "1500W"},
        "tags": ["空气炸锅", "厨房小家电", "易清洗", "占地小"],
        "suitable_scene": ["租房", "厨房", "做饭"],
        "stock": 30,
        "stock_status": "in_stock",
        "review_summary": "容量适中，清洗方便，适合一到两人租房厨房。",
    },
    {
        "id": 1302,
        "name": "SoloCook 1.8L 多功能电煮锅",
        "category": "电煮锅",
        "brand": "HomeChef",
        "sku": "demo-broad-cooker-solocook-18",
        "price": Decimal("169.00"),
        "original_price": Decimal("219.00"),
        "platform": "天猫",
        "product_url": "https://www.mi.com/global/product/mi-smart-kettle-pro/",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/beta-powerbank-anker-laptop-25k-165w/A1695H11_TD01_V1-2cb9bc87c5220780.png",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/beta-powerbank-anker-laptop-25k-165w/A1695H11_TD01_V1-2cb9bc87c5220780.png"],
        "rating": Decimal("4.50"),
        "sales": 1800,
        "description": "小体积电煮锅，可煮面、煮汤和简单火锅，适合租房和宿舍。",
        "specs": {"capacity": "1.8L", "levels": "两档火力", "pot": "不粘内胆"},
        "tags": ["电煮锅", "厨房小家电", "小巧", "性价比"],
        "suitable_scene": ["租房", "宿舍", "做饭"],
        "stock": 48,
        "stock_status": "in_stock",
        "review_summary": "体积小，做一人餐方便，收纳压力低。",
    },
    {
        "id": 1303,
        "name": "PetClean V8 低噪吸尘器",
        "category": "吸尘器",
        "brand": "CleanLab",
        "sku": "demo-broad-vacuum-petclean-v8",
        "price": Decimal("699.00"),
        "original_price": Decimal("899.00"),
        "platform": "京东",
        "product_url": "https://us.roborock.com/pages/roborock-h5",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-mouse-ergo-m2/lift-mouse-top-angle-graphite-gallery-1-ad5bae12e4353922.webp",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-mouse-ergo-m2/lift-mouse-top-angle-graphite-gallery-1-ad5bae12e4353922.webp"],
        "rating": Decimal("4.80"),
        "sales": 1600,
        "description": "无线吸尘器，配宠物毛发刷头，噪音控制较好，尘杯拆洗方便。",
        "specs": {"suction": "160AW", "battery": "45分钟", "brush": "防缠绕毛发刷"},
        "tags": ["吸尘器", "清洁机", "吸猫毛", "低噪音"],
        "suitable_scene": ["宠物", "清洁", "客厅"],
        "stock": 24,
        "stock_status": "in_stock",
        "review_summary": "吸猫毛效果稳定，维护简单，适合养宠家庭日常清洁。",
    },
    {
        "id": 1304,
        "name": "RunFit S3 长续航智能手表",
        "category": "智能手表",
        "brand": "RunFit",
        "sku": "demo-broad-watch-runfit-s3",
        "price": Decimal("899.00"),
        "original_price": Decimal("1199.00"),
        "platform": "天猫",
        "product_url": "https://consumer.huawei.com/en/wearables/",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-headphone-studiobuds-max/A3028013_product_image_01_V1-196ad3bf3a0a03bb.webp",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-headphone-studiobuds-max/A3028013_product_image_01_V1-196ad3bf3a0a03bb.webp"],
        "rating": Decimal("4.60"),
        "sales": 980,
        "description": "智能手表支持跑步、力量训练和全天心率记录，续航约 10 天。",
        "specs": {"battery": "10天", "sports": "100+ 运动模式", "health": "心率/睡眠"},
        "tags": ["智能手表", "手表", "续航好", "运动"],
        "suitable_scene": ["运动", "跑步", "健身"],
        "stock": 32,
        "stock_status": "in_stock",
        "review_summary": "续航稳定，运动记录清晰，佩戴重量适中。",
    },
    {
        "id": 1305,
        "name": "CinemaCube Mini 卧室投影仪",
        "category": "投影仪",
        "brand": "ViewLab",
        "sku": "demo-broad-projector-cinemacube-mini",
        "price": Decimal("1299.00"),
        "original_price": Decimal("1599.00"),
        "platform": "京东",
        "product_url": "https://us.xgimi.com/",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-monitor-clearview-24/studio-display_overview__cc7vair07fjm_og-7e46f6424f873aab.png",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-monitor-clearview-24/studio-display_overview__cc7vair07fjm_og-7e46f6424f873aab.png"],
        "rating": Decimal("4.70"),
        "sales": 1200,
        "description": "卧室投影仪，支持自动校正，噪音低，适合夜间看电影。",
        "specs": {"resolution": "1080p", "correction": "自动梯形校正", "noise": "低噪模式"},
        "tags": ["投影仪", "自动校正", "低噪音", "画面清楚"],
        "suitable_scene": ["卧室", "看电影", "租房"],
        "stock": 18,
        "stock_status": "in_stock",
        "review_summary": "自动校正省事，卧室使用亮度和噪音表现均衡。",
    },
    {
        "id": 1306,
        "name": "CommuteCup 360 防漏保温咖啡杯",
        "category": "咖啡杯",
        "brand": "CupLab",
        "sku": "demo-broad-cup-commutecup-360",
        "price": Decimal("149.00"),
        "original_price": Decimal("199.00"),
        "platform": "天猫",
        "product_url": "https://www.mi.com/global/product/xiaomi-mijia-thermos-flask/",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-powerstrip-safestrip-4/A9125001_1200x1200-168a70ff1d619e09.webp",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-powerstrip-safestrip-4/A9125001_1200x1200-168a70ff1d619e09.webp"],
        "rating": Decimal("4.50"),
        "sales": 2200,
        "description": "360ml 防漏咖啡杯，保温表现稳定，杯盖可拆洗，适合办公室和通勤。",
        "specs": {"capacity": "360ml", "seal": "防漏杯盖", "material": "316不锈钢"},
        "tags": ["咖啡杯", "保温杯", "不漏水", "易清洗"],
        "suitable_scene": ["办公", "通勤", "旅行"],
        "stock": 60,
        "stock_status": "in_stock",
        "review_summary": "密封可靠，清洗方便，放包里通勤更安心。",
    },
    {
        "id": 1307,
        "name": "KidStudy Pad 10 护眼学习平板",
        "category": "学习平板",
        "brand": "StudyLab",
        "sku": "demo-broad-tablet-kidstudy-10",
        "price": Decimal("1399.00"),
        "original_price": Decimal("1699.00"),
        "platform": "京东",
        "product_url": "https://www.lenovo.com/us/en/tablets/",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-laptop-codebook-air-14/lenovo-thinkpad-p14s-gen-5-14-intel-01-77b046b1832bb7fd.webp",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-laptop-codebook-air-14/lenovo-thinkpad-p14s-gen-5-14-intel-01-77b046b1832bb7fd.webp"],
        "rating": Decimal("4.60"),
        "sales": 740,
        "description": "儿童学习平板，带护眼模式、内容管控和家长管理，适合小学阶段学习。",
        "specs": {"screen": "10.4英寸", "storage": "128GB", "parent_control": "支持"},
        "tags": ["学习平板", "平板", "护眼", "内容可控"],
        "suitable_scene": ["学习", "上课", "小学"],
        "stock": 20,
        "stock_status": "in_stock",
        "review_summary": "护眼和家长管理功能完整，适合孩子上课和课后练习。",
    },
]
