"""Deterministic products for live demo flows."""

from __future__ import annotations

from decimal import Decimal
from typing import Any


DEMO_SHOWCASE_PRODUCTS: list[dict[str, Any]] = [
    {
        "id": 1101,
        "name": "Campus75 三模静音机械键盘",
        "category": "机械键盘",
        "brand": "KeyNova",
        "sku": "demo-keyboard-campus75",
        "price": Decimal("289.00"),
        "original_price": Decimal("359.00"),
        "platform": "京东",
        "product_url": "https://example.com/products/demo-keyboard-campus75",
        "image_url": "https://example.com/images/demo-keyboard-campus75.jpg",
        "image_urls": ["https://example.com/images/demo-keyboard-campus75.jpg"],
        "rating": Decimal("4.90"),
        "sales": 2600,
        "description": "75 配列三模连接，静音轴体，适合宿舍夜间写代码。",
        "specs": {"layout": "75键", "switch": "静音线性轴", "connection": "蓝牙/2.4G/有线"},
        "tags": ["低噪音", "无线", "三模", "性价比"],
        "suitable_scene": ["宿舍", "写代码", "学习"],
        "stock": 36,
        "stock_status": "in_stock",
        "review_summary": "声音控制好，宿舍夜间使用压力小。",
    },
    {
        "id": 1102,
        "name": "MetroBuds Lite 通勤降噪耳机",
        "category": "蓝牙耳机",
        "brand": "SoundAir",
        "sku": "demo-earbuds-metro-lite",
        "price": Decimal("299.00"),
        "original_price": Decimal("399.00"),
        "platform": "天猫",
        "product_url": "https://example.com/products/demo-earbuds-metro-lite",
        "image_url": "https://example.com/images/demo-earbuds-metro-lite.jpg",
        "image_urls": ["https://example.com/images/demo-earbuds-metro-lite.jpg"],
        "rating": Decimal("4.70"),
        "sales": 3100,
        "description": "轻量入耳式主动降噪耳机，适合地铁通勤和办公电话。",
        "specs": {"noise_canceling": "ANC主动降噪", "battery": "28小时", "weight": "4.5g/只"},
        "tags": ["降噪", "轻便", "无线", "通勤"],
        "suitable_scene": ["通勤", "办公", "学习"],
        "stock": 52,
        "stock_status": "in_stock",
        "review_summary": "降噪够用，佩戴轻，适合每天通勤。",
    },
    {
        "id": 1103,
        "name": "FocusLamp Mini 宿舍护眼台灯",
        "category": "台灯",
        "brand": "LightWise",
        "sku": "demo-lamp-focus-mini",
        "price": Decimal("199.00"),
        "original_price": Decimal("259.00"),
        "platform": "京东",
        "product_url": "https://example.com/products/demo-lamp-focus-mini",
        "image_url": "https://example.com/images/demo-lamp-focus-mini.jpg",
        "image_urls": ["https://example.com/images/demo-lamp-focus-mini.jpg"],
        "rating": Decimal("4.60"),
        "sales": 1400,
        "description": "小底座护眼台灯，占桌面少，适合宿舍学习和备考。",
        "specs": {"brightness": "900lx", "color_temp": "3000K-5000K", "base": "小底座"},
        "tags": ["护眼", "小巧", "学习", "宿舍"],
        "suitable_scene": ["宿舍", "学习", "阅读"],
        "stock": 44,
        "stock_status": "in_stock",
        "review_summary": "桌面占用少，亮度覆盖一人学习区。",
    },
    {
        "id": 1104,
        "name": "TravelGo 10000mAh 轻薄充电宝",
        "category": "充电宝",
        "brand": "PowerMax",
        "sku": "demo-powerbank-travelgo-10000",
        "price": Decimal("129.00"),
        "original_price": Decimal("169.00"),
        "platform": "天猫",
        "product_url": "https://example.com/products/demo-powerbank-travelgo-10000",
        "image_url": "https://example.com/images/demo-powerbank-travelgo-10000.jpg",
        "image_urls": ["https://example.com/images/demo-powerbank-travelgo-10000.jpg"],
        "rating": Decimal("4.50"),
        "sales": 2800,
        "description": "轻薄便携，支持 20W 快充，适合通勤随身携带。",
        "specs": {"capacity": "10000mAh", "output": "20W", "weight": "185g"},
        "tags": ["轻便", "快充", "通勤", "性价比"],
        "suitable_scene": ["通勤", "旅行", "应急"],
        "stock": 70,
        "stock_status": "in_stock",
        "review_summary": "重量控制好，日常补电足够。",
    },
    {
        "id": 1105,
        "name": "CityPack 轻量通勤双肩包",
        "category": "双肩包",
        "brand": "PackLab",
        "sku": "demo-backpack-citypack",
        "price": Decimal("239.00"),
        "original_price": Decimal("319.00"),
        "platform": "京东",
        "product_url": "https://example.com/products/demo-backpack-citypack",
        "image_url": "https://example.com/images/demo-backpack-citypack.jpg",
        "image_urls": ["https://example.com/images/demo-backpack-citypack.jpg"],
        "rating": Decimal("4.70"),
        "sales": 1700,
        "description": "轻量防泼水通勤包，独立电脑仓，适合上课和办公。",
        "specs": {"capacity": "22L", "laptop": "15.6英寸", "material": "防泼水尼龙"},
        "tags": ["轻便", "防泼水", "电脑仓", "通勤"],
        "suitable_scene": ["通勤", "办公", "学习"],
        "stock": 28,
        "stock_status": "in_stock",
        "review_summary": "背负轻，电脑仓保护比较稳。",
    },
]
