"""Deterministic products for live demo flows."""

from __future__ import annotations

from decimal import Decimal
from typing import Any


DEMO_SHOWCASE_PRODUCTS: list[dict[str, Any]] = [
    {
        "id": 1101,
        "name": "Campus75 三模静音机械键盘",
        "category": "机械键盘",
        "brand": "KeyNova",
        "sku": "demo-keyboard-campus75",
        "price": Decimal("289.00"),
        "original_price": Decimal("359.00"),
        "platform": "京东",
        "product_url": "https://nuphy.com/products/air75-v3",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/beta-keyboard-keychron-k3-max-se/Keychron-K3-Max-SE-features-451e731bc6f18fcc.jpg",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/beta-keyboard-keychron-k3-max-se/Keychron-K3-Max-SE-features-451e731bc6f18fcc.jpg"],
        "rating": Decimal("4.90"),
        "sales": 2600,
        "description": "75 配列三模连接，静音轴体，适合宿舍夜间写代码。",
        "specs": {"layout": "75键", "switch": "静音线性轴", "connection": "蓝牙/2.4G/有线"},
        "tags": ["低噪音", "无线", "三模", "性价比"],
        "suitable_scene": ["宿舍", "写代码", "学习"],
        "stock": 36,
        "stock_status": "in_stock",
        "review_summary": "声音控制好，宿舍夜间使用压力小。",
    },
    {
        "id": 1102,
        "name": "MetroBuds Lite 通勤降噪耳机",
        "category": "蓝牙耳机",
        "brand": "SoundAir",
        "sku": "demo-earbuds-metro-lite",
        "price": Decimal("299.00"),
        "original_price": Decimal("399.00"),
        "platform": "天猫",
        "product_url": "https://www.soundcore.com/products/liberty-4-nc-a3947z11",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/beta-earbuds-soundcore-liberty-4-nc/A3947Z11_4088025e-9f6e-4ec4-ad98-69d8d7dbf357-6e213c5f2636a16a.png",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/beta-earbuds-soundcore-liberty-4-nc/A3947Z11_4088025e-9f6e-4ec4-ad98-69d8d7dbf357-6e213c5f2636a16a.png"],
        "rating": Decimal("4.70"),
        "sales": 3100,
        "description": "轻量入耳式主动降噪耳机，适合地铁通勤和办公电话。",
        "specs": {"noise_canceling": "ANC主动降噪", "battery": "28小时", "weight": "4.5g/只"},
        "tags": ["降噪", "轻便", "无线", "通勤"],
        "suitable_scene": ["通勤", "办公", "学习"],
        "stock": 52,
        "stock_status": "in_stock",
        "review_summary": "降噪够用，佩戴轻，适合每天通勤。",
    },
    {
        "id": 1103,
        "name": "FocusLamp Mini 宿舍护眼台灯",
        "category": "台灯",
        "brand": "LightWise",
        "sku": "demo-lamp-focus-mini",
        "price": Decimal("199.00"),
        "original_price": Decimal("259.00"),
        "platform": "京东",
        "product_url": "https://www.benq.com/en-us/lighting/e-reading-desk-lamp/genie.html",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/beta-lamp-benq-genie/silver-4-61e4114f52932eb8.jpg",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/beta-lamp-benq-genie/silver-4-61e4114f52932eb8.jpg"],
        "rating": Decimal("4.60"),
        "sales": 1400,
        "description": "小底座护眼台灯，占桌面少，适合宿舍学习和备考。",
        "specs": {"brightness": "900lx", "color_temp": "3000K-5000K", "base": "小底座"},
        "tags": ["护眼", "小巧", "学习", "宿舍"],
        "suitable_scene": ["宿舍", "学习", "阅读"],
        "stock": 44,
        "stock_status": "in_stock",
        "review_summary": "桌面占用少，亮度覆盖一人学习区。",
    },
    {
        "id": 1104,
        "name": "TravelGo 10000mAh 轻薄充电宝",
        "category": "充电宝",
        "brand": "PowerMax",
        "sku": "demo-powerbank-travelgo-10000",
        "price": Decimal("129.00"),
        "original_price": Decimal("169.00"),
        "platform": "天猫",
        "product_url": "https://www.anker.com/products/a1695-anker-power-bank-25000mah-165w",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/beta-powerbank-anker-laptop-25k-165w/A1695H11_TD01_V1-2cb9bc87c5220780.png",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/beta-powerbank-anker-laptop-25k-165w/A1695H11_TD01_V1-2cb9bc87c5220780.png"],
        "rating": Decimal("4.50"),
        "sales": 2800,
        "description": "轻薄便携，支持 20W 快充，适合通勤随身携带。",
        "specs": {"capacity": "10000mAh", "output": "20W", "weight": "185g"},
        "tags": ["轻便", "快充", "通勤", "性价比"],
        "suitable_scene": ["通勤", "旅行", "应急"],
        "stock": 70,
        "stock_status": "in_stock",
        "review_summary": "重量控制好，日常补电足够。",
    },
    {
        "id": 1105,
        "name": "CityPack 轻量通勤双肩包",
        "category": "双肩包",
        "brand": "PackLab",
        "sku": "demo-backpack-citypack",
        "price": Decimal("239.00"),
        "original_price": Decimal("319.00"),
        "platform": "京东",
        "product_url": "https://www.thenorthface.com/en-us/p/bags-and-gear/backpacks-224451/borealis-backpack-NF0A52SE?color=NK5",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/beta-backpack-tnf-borealis/Borealis-Backpack-TNF-HERO-331fa791a66ccf1b.png",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/beta-backpack-tnf-borealis/Borealis-Backpack-TNF-HERO-331fa791a66ccf1b.png"],
        "rating": Decimal("4.70"),
        "sales": 1700,
        "description": "轻量防泼水通勤包，独立电脑仓，适合上课和办公。",
        "specs": {"capacity": "22L", "laptop": "15.6英寸", "material": "防泼水尼龙"},
        "tags": ["轻便", "防泼水", "电脑仓", "通勤"],
        "suitable_scene": ["通勤", "办公", "学习"],
        "stock": 28,
        "stock_status": "in_stock",
        "review_summary": "背负轻，电脑仓保护比较稳。",
    },
    {
        "id": 1201,
        "name": "DeskMini S 入门迷你主机",
        "category": "电脑",
        "brand": "DeskCore",
        "sku": "demo-desktop-deskmini-s",
        "price": Decimal("2599.00"),
        "original_price": Decimal("2999.00"),
        "platform": "京东",
        "product_url": "https://www.apple.com/mac-mini/",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-desktop-deskmini-s/mac-mini__dvce2jrm11w2_og-144a2392f389dac8.jpg",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-desktop-deskmini-s/mac-mini__dvce2jrm11w2_og-144a2392f389dac8.jpg"],
        "rating": Decimal("4.50"),
        "sales": 860,
        "description": "小体积迷你主机，适合宿舍学习、网课和轻办公。",
        "specs": {"cpu": "6核处理器", "memory": "16GB", "storage": "512GB SSD"},
        "tags": ["小巧", "办公", "性价比"],
        "suitable_scene": ["宿舍", "办公", "学习"],
        "stock": 18,
        "stock_status": "in_stock",
        "review_summary": "体积小，日常办公和学习足够。",
    },
    {
        "id": 1202,
        "name": "CodeBook Air 14 轻薄本",
        "category": "电脑",
        "brand": "DeskCore",
        "sku": "demo-laptop-codebook-air-14",
        "price": Decimal("4599.00"),
        "original_price": Decimal("5299.00"),
        "platform": "天猫",
        "product_url": "https://www.lenovo.com/us/en/p/laptops/thinkpad/thinkpadt/thinkpad-t14-gen-6-14-inch-amd/len101t0106",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-laptop-codebook-air-14/lenovo-thinkpad-p14s-gen-5-14-intel-01-77b046b1832bb7fd.webp",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-laptop-codebook-air-14/lenovo-thinkpad-p14s-gen-5-14-intel-01-77b046b1832bb7fd.webp"],
        "rating": Decimal("4.70"),
        "sales": 1200,
        "description": "14 英寸轻薄本，适合编程、办公和课堂携带。",
        "specs": {"screen": "14英寸", "memory": "16GB", "storage": "1TB SSD"},
        "tags": ["轻便", "办公", "写代码"],
        "suitable_scene": ["办公", "学习", "写代码"],
        "stock": 24,
        "stock_status": "in_stock",
        "review_summary": "续航和便携性较均衡。",
    },
    {
        "id": 1203,
        "name": "CreatorBox P 高配桌面主机",
        "category": "电脑",
        "brand": "DeskCore",
        "sku": "demo-desktop-creatorbox-p",
        "price": Decimal("6999.00"),
        "original_price": Decimal("7599.00"),
        "platform": "京东",
        "product_url": "https://www.apple.com/mac-studio/",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-desktop-creatorbox-p/mac-studio_overview__eedzbosm1t26_og-b0fce74e86d96e1b.png",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-desktop-creatorbox-p/mac-studio_overview__eedzbosm1t26_og-b0fce74e86d96e1b.png"],
        "rating": Decimal("4.80"),
        "sales": 640,
        "description": "性能余量更高的桌面主机，适合编程、多任务和轻度游戏。",
        "specs": {"cpu": "8核处理器", "gpu": "独立显卡", "memory": "32GB"},
        "tags": ["高性能", "写代码", "办公"],
        "suitable_scene": ["办公", "写代码", "学习"],
        "stock": 12,
        "stock_status": "in_stock",
        "review_summary": "多任务余量更好，适合长期桌面使用。",
    },
    {
        "id": 1204,
        "name": "ClearView 24 护眼显示器",
        "category": "显示器",
        "brand": "ViewLab",
        "sku": "demo-monitor-clearview-24",
        "price": Decimal("799.00"),
        "original_price": Decimal("999.00"),
        "platform": "京东",
        "product_url": "https://www.apple.com/studio-display/",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-monitor-clearview-24/studio-display_overview__cc7vair07fjm_og-7e46f6424f873aab.png",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-monitor-clearview-24/studio-display_overview__cc7vair07fjm_og-7e46f6424f873aab.png"],
        "rating": Decimal("4.60"),
        "sales": 1800,
        "description": "24 英寸护眼显示器，适合宿舍和小桌面。",
        "specs": {"size": "24英寸", "resolution": "1080p", "refresh_rate": "75Hz"},
        "tags": ["护眼", "小巧", "办公"],
        "suitable_scene": ["宿舍", "办公", "学习"],
        "stock": 38,
        "stock_status": "in_stock",
        "review_summary": "尺寸适中，小桌面也容易摆放。",
    },
    {
        "id": 1205,
        "name": "SharpView 27 2K 办公显示器",
        "category": "显示器",
        "brand": "ViewLab",
        "sku": "demo-monitor-sharpview-27",
        "price": Decimal("1299.00"),
        "original_price": Decimal("1599.00"),
        "platform": "天猫",
        "product_url": "https://www.asus.com/displays-desktops/monitors/tuf-gaming/tuf-gaming-vg27aq3a/",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-monitor-sharpview-27/kv1-e0bb59f7bf7d8f9f.jpg",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-monitor-sharpview-27/kv1-e0bb59f7bf7d8f9f.jpg"],
        "rating": Decimal("4.70"),
        "sales": 1500,
        "description": "27 英寸 2K 显示器，适合编程、文档和多窗口办公。",
        "specs": {"size": "27英寸", "resolution": "2K", "refresh_rate": "100Hz"},
        "tags": ["护眼", "办公", "写代码"],
        "suitable_scene": ["办公", "写代码", "学习"],
        "stock": 30,
        "stock_status": "in_stock",
        "review_summary": "文字清晰，多窗口效率更高。",
    },
    {
        "id": 1206,
        "name": "FlowView 27 高刷显示器",
        "category": "显示器",
        "brand": "ViewLab",
        "sku": "demo-monitor-flowview-27",
        "price": Decimal("1999.00"),
        "original_price": Decimal("2399.00"),
        "platform": "京东",
        "product_url": "https://www.asus.com/displays-desktops/monitors/tuf-gaming/tuf-gaming-vg27aq3a/",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-monitor-flowview-27/bg_console-fe728fc54225dcbb.jpg",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-monitor-flowview-27/bg_console-fe728fc54225dcbb.jpg"],
        "rating": Decimal("4.80"),
        "sales": 980,
        "description": "高刷显示器，兼顾办公流畅度和轻度游戏。",
        "specs": {"size": "27英寸", "resolution": "2K", "refresh_rate": "165Hz"},
        "tags": ["高刷", "办公", "游戏"],
        "suitable_scene": ["办公", "写代码"],
        "stock": 16,
        "stock_status": "in_stock",
        "review_summary": "拖动窗口和轻度游戏更顺滑。",
    },
    {
        "id": 1207,
        "name": "QuietMouse M1 静音办公鼠标",
        "category": "鼠标",
        "brand": "PointLab",
        "sku": "demo-mouse-quiet-m1",
        "price": Decimal("89.00"),
        "original_price": Decimal("129.00"),
        "platform": "京东",
        "product_url": "https://www.logitech.com/en-us/products/mice/mx-master-3s.910-006556.html",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-mouse-quiet-m1/mx-master-3s-bluetooth-edition-top-view-black-new-1-dcb20aa8b53ac4c1.webp",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-mouse-quiet-m1/mx-master-3s-bluetooth-edition-top-view-black-new-1-dcb20aa8b53ac4c1.webp"],
        "rating": Decimal("4.50"),
        "sales": 2200,
        "description": "静音点击，适合宿舍和办公室。",
        "specs": {"connection": "无线", "dpi": "1600", "battery": "12个月"},
        "tags": ["静音", "无线", "办公"],
        "suitable_scene": ["宿舍", "办公", "学习"],
        "stock": 80,
        "stock_status": "in_stock",
        "review_summary": "点击声小，日常办公够用。",
    },
    {
        "id": 1208,
        "name": "ErgoMouse M2 人体工学鼠标",
        "category": "鼠标",
        "brand": "PointLab",
        "sku": "demo-mouse-ergo-m2",
        "price": Decimal("199.00"),
        "original_price": Decimal("259.00"),
        "platform": "天猫",
        "product_url": "https://www.logitech.com/en-us/products/mice/lift-vertical-ergonomic-mouse.html",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-mouse-ergo-m2/lift-mouse-top-angle-graphite-gallery-1-ad5bae12e4353922.webp",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-mouse-ergo-m2/lift-mouse-top-angle-graphite-gallery-1-ad5bae12e4353922.webp"],
        "rating": Decimal("4.70"),
        "sales": 1300,
        "description": "人体工学握持，适合长时间办公和编程。",
        "specs": {"connection": "蓝牙/2.4G", "dpi": "4000", "buttons": "6键"},
        "tags": ["人体工学", "无线", "办公"],
        "suitable_scene": ["办公", "写代码"],
        "stock": 42,
        "stock_status": "in_stock",
        "review_summary": "长时间使用手腕压力更小。",
    },
    {
        "id": 1209,
        "name": "SwiftMouse G3 高性能鼠标",
        "category": "鼠标",
        "brand": "PointLab",
        "sku": "demo-mouse-swift-g3",
        "price": Decimal("349.00"),
        "original_price": Decimal("429.00"),
        "platform": "京东",
        "product_url": "https://www.razer.com/gaming-mice/razer-viper-v3-pro",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-mouse-swift-g3/razer-viper-v3-pro-1200x630-ab43835a34c3f9ea.webp",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-mouse-swift-g3/razer-viper-v3-pro-1200x630-ab43835a34c3f9ea.webp"],
        "rating": Decimal("4.80"),
        "sales": 900,
        "description": "轻量高性能鼠标，适合轻度游戏和高频操作。",
        "specs": {"connection": "2.4G/有线", "dpi": "26000", "weight": "59g"},
        "tags": ["轻便", "游戏", "无线"],
        "suitable_scene": ["办公", "写代码"],
        "stock": 20,
        "stock_status": "in_stock",
        "review_summary": "重量轻，移动响应快。",
    },
    {
        "id": 1210,
        "name": "StudioBuds Max 头戴降噪耳机",
        "category": "蓝牙耳机",
        "brand": "SoundAir",
        "sku": "demo-headphone-studiobuds-max",
        "price": Decimal("699.00"),
        "original_price": Decimal("899.00"),
        "platform": "京东",
        "product_url": "https://www.soundcore.com/products/a3028011",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-headphone-studiobuds-max/A3028013_product_image_01_V1-196ad3bf3a0a03bb.webp",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-headphone-studiobuds-max/A3028013_product_image_01_V1-196ad3bf3a0a03bb.webp"],
        "rating": Decimal("4.80"),
        "sales": 760,
        "description": "头戴式降噪耳机，适合会议、专注办公和宿舍学习。",
        "specs": {"noise_canceling": "ANC主动降噪", "battery": "45小时", "weight": "245g"},
        "tags": ["降噪", "办公", "无线"],
        "suitable_scene": ["办公", "学习", "宿舍"],
        "stock": 26,
        "stock_status": "in_stock",
        "review_summary": "降噪和通话表现更稳。",
    },
    {
        "id": 1211,
        "name": "FlexArm 显示器支架",
        "category": "支架",
        "brand": "DeskFit",
        "sku": "demo-stand-flexarm",
        "price": Decimal("169.00"),
        "original_price": Decimal("229.00"),
        "platform": "天猫",
        "product_url": "https://www.twelvesouth.com/products/curve-for-macbook",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-stand-flexarm/12S_Curve_White_ChildHero-65855ed8cfc2103c.webp",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-stand-flexarm/12S_Curve_White_ChildHero-65855ed8cfc2103c.webp"],
        "rating": Decimal("4.60"),
        "sales": 1100,
        "description": "显示器支架，释放桌面空间并改善视线高度。",
        "specs": {"support": "17-32英寸", "load": "9kg", "mount": "夹桌/穿孔"},
        "tags": ["桌面", "办公", "小巧"],
        "suitable_scene": ["办公", "写代码", "宿舍"],
        "stock": 34,
        "stock_status": "in_stock",
        "review_summary": "桌面更清爽，屏幕高度更好调。",
    },
    {
        "id": 1212,
        "name": "BookStand Pro 笔记本支架",
        "category": "支架",
        "brand": "DeskFit",
        "sku": "demo-stand-bookstand-pro",
        "price": Decimal("99.00"),
        "original_price": Decimal("139.00"),
        "platform": "京东",
        "product_url": "https://www.twelvesouth.com/products/curve-for-macbook",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-stand-bookstand-pro/12S_Curve_Black_ChildHero-b3a3f3f9bffbc8c2.webp",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-stand-bookstand-pro/12S_Curve_Black_ChildHero-b3a3f3f9bffbc8c2.webp"],
        "rating": Decimal("4.50"),
        "sales": 1400,
        "description": "笔记本支架，适合外接键鼠和显示器使用。",
        "specs": {"material": "铝合金", "foldable": "否", "support": "11-16英寸"},
        "tags": ["小巧", "办公", "学习"],
        "suitable_scene": ["办公", "学习", "宿舍"],
        "stock": 50,
        "stock_status": "in_stock",
        "review_summary": "抬高屏幕后颈部压力更小。",
    },
    {
        "id": 1213,
        "name": "PortHub 8 合 1 拓展坞",
        "category": "拓展坞",
        "brand": "PortLab",
        "sku": "demo-dock-porthub-8in1",
        "price": Decimal("199.00"),
        "original_price": Decimal("259.00"),
        "platform": "京东",
        "product_url": "https://www.anker.com/products/a8392",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-dock-deskdock-pro/main.png",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-dock-deskdock-pro/main.png"],
        "rating": Decimal("4.60"),
        "sales": 980,
        "description": "8 合 1 USB-C 拓展坞，补齐显示、网口和 USB 接口。",
        "specs": {"ports": "HDMI/USB-A/USB-C/网口", "power": "100W PD", "display": "4K HDMI"},
        "tags": ["办公", "接口", "小巧"],
        "suitable_scene": ["办公", "写代码", "学习"],
        "stock": 45,
        "stock_status": "in_stock",
        "review_summary": "接口够用，适合轻薄本桌面化。",
    },
    {
        "id": 1214,
        "name": "DeskDock Pro 双屏拓展坞",
        "category": "拓展坞",
        "brand": "PortLab",
        "sku": "demo-dock-deskdock-pro",
        "price": Decimal("499.00"),
        "original_price": Decimal("599.00"),
        "platform": "天猫",
        "product_url": "https://www.anker.com/products/a8383",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-dock-porthub-8in1/A83830A3_TD01_533634ef-bb62-4009-92e0-a96c3a3d6a4d-11a14af5e0d287ec.webp",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-dock-porthub-8in1/A83830A3_TD01_533634ef-bb62-4009-92e0-a96c3a3d6a4d-11a14af5e0d287ec.webp"],
        "rating": Decimal("4.70"),
        "sales": 520,
        "description": "更高规格拓展坞，适合双屏和固定桌面工作站。",
        "specs": {"ports": "双HDMI/USB-C/网口", "power": "100W PD", "display": "双屏输出"},
        "tags": ["办公", "高性能", "接口"],
        "suitable_scene": ["办公", "写代码"],
        "stock": 18,
        "stock_status": "in_stock",
        "review_summary": "适合固定工位，接口余量更足。",
    },
    {
        "id": 1215,
        "name": "SafeStrip 4 位防雷插排",
        "category": "插排",
        "brand": "PowerDesk",
        "sku": "demo-powerstrip-safestrip-4",
        "price": Decimal("69.00"),
        "original_price": Decimal("89.00"),
        "platform": "京东",
        "product_url": "https://www.anker.com/products/a9192",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-powerstrip-chargestrip-65w/main.png",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-powerstrip-chargestrip-65w/main.png"],
        "rating": Decimal("4.50"),
        "sales": 2600,
        "description": "基础防雷插排，适合宿舍和桌面设备供电。",
        "specs": {"sockets": "4位", "usb": "无", "cable": "1.8m"},
        "tags": ["安全", "宿舍", "性价比"],
        "suitable_scene": ["宿舍", "办公", "学习"],
        "stock": 90,
        "stock_status": "in_stock",
        "review_summary": "基础供电够用，安全性更稳。",
    },
    {
        "id": 1216,
        "name": "ChargeStrip 65W 桌面插排",
        "category": "插排",
        "brand": "PowerDesk",
        "sku": "demo-powerstrip-chargestrip-65w",
        "price": Decimal("169.00"),
        "original_price": Decimal("219.00"),
        "platform": "天猫",
        "product_url": "https://www.ankerjapan.com/products/a9125",
        "image_url": "https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-powerstrip-safestrip-4/A9125001_1200x1200-168a70ff1d619e09.webp",
        "image_urls": ["https://buywise-1392410096.cos.ap-guangzhou.myqcloud.com/product-images/demo-powerstrip-safestrip-4/A9125001_1200x1200-168a70ff1d619e09.webp"],
        "rating": Decimal("4.70"),
        "sales": 1500,
        "description": "带 65W USB-C 的桌面插排，可同时给笔记本和外设供电。",
        "specs": {"sockets": "3位", "usb_c": "65W", "cable": "1.5m"},
        "tags": ["快充", "办公", "桌面"],
        "suitable_scene": ["办公", "写代码", "宿舍"],
        "stock": 40,
        "stock_status": "in_stock",
        "review_summary": "桌面充电更简洁，减少充电头数量。",
    },
]
